module.exports = components = {
    paths: {
        Accordion: "./src/Accordion/index.ts",
        Breadcrumb: "./src/Breadcrumb/index.ts",
        Button: "./src/Button/index.ts",
        Carousel: "./src/Carousel/index.ts",
        Chart: "./src/Chart/index.ts",
        CheckBox: "./src/CheckBox/index.ts",
        Datepicker: "./src/Datepicker/index.ts",
        Dialogue: "./src/Dialogue/index.ts",
        Dropdown: "./src/Dropdown/index.ts",
        Icon: "./src/Icon/index.ts",
        Image: "./src/Image/index.ts",
        InlineLink: "./src/InlineLink/index.ts",
        Loader: "./src/Loader/index.ts",
        Modal: "./src/Modal/index.ts",
        Notification: "./src/Notification/index.ts",
        Pagination: "./src/Pagination/index.ts",
        ProgressBar: "./src/ProgressBar/index.ts",
        RadioButton: "./src/RadioButton/index.ts",
        RadioGroup: "./src/RadioGroup/index.ts",
        Rating: "./src/Rating/index.ts",
        Slider: "./src/Slider/index.ts",
        Stepper: "./src/Stepper/index.ts",
        StepTracker: "./src/StepTracker/index.ts",
        Tabs: "./src/Tabs/index.ts",
        Table: "./src/Table/index.ts",
        TextArea: "./src/TextArea/index.ts",
        TextBox: "./src/TextBox/index.ts",
        TextBoxGroup: "./src/TextBoxGroup/index.ts",
        TextLabel: "./src/TextLabel/index.ts",
        Timeline: "./src/Timeline/index.ts",
        Timepicker: "./src/Timepicker/index.ts",
        Toggle: "./src/Toggle/index.ts",
        Tooltip: "./src/Tooltip/index.ts",
        Video: "./src/Video/index.ts",
        ImageCropper: "./src/ImageCropper/index.ts",
        Timer: "./src/Timer/index.ts"
    },
    indexes: [
        { from: "./src/Accordion/index.ts", to: "./Accordion/index.js" },
        { from: "./src/Breadcrumb/index.ts", to: "./Breadcrumb/index.js" },
        { from: "./src/Button/index.ts", to: "./Button/index.js" },
        { from: "./src/Carousel/index.ts", to: "./Carousel/index.js" },
        { from: "./src/Chart/index.ts", to: "./Chart/index.js" },
        { from: "./src/CheckBox/index.ts", to: "./CheckBox/index.js" },
        { from: "./src/Datepicker/index.ts", to: "./Datepicker/index.js" },
        { from: "./src/Dialogue/index.ts", to: "./Dialogue/index.js" },
        { from: "./src/Dropdown/index.ts", to: "./Dropdown/index.js" },
        { from: "./src/Icon/index.ts", to: "./Icon/index.js" },
        { from: "./src/Image/index.ts", to: "./Image/index.js" },
        { from: "./src/InlineLink/index.ts", to: "./InlineLink/index.js" },
        { from: "./src/Loader/index.ts", to: "./Loader/index.js" },
        { from: "./src/Modal/index.ts", to: "./Modal/index.js" },
        { from: "./src/Notification/index.ts", to: "./Notification/index.js" },
        { from: "./src/Pagination/index.ts", to: "./Pagination/index.js" },
        { from: "./src/ProgressBar/index.ts", to: "./ProgressBar/index.js" },
        { from: "./src/RadioButton/index.ts", to: "./RadioButton/index.js" },
        { from: "./src/RadioGroup/index.ts", to: "./RadioGroup/index.js" },
        { from: "./src/Rating/index.ts", to: "./Rating/index.js" },
        { from: "./src/Slider/index.ts", to: "./Slider/index.js" },
        { from: "./src/Stepper/index.ts", to: "./Stepper/index.js" },
        { from: "./src/StepTracker/index.ts", to: "./StepTracker/index.js" },
        { from: "./src/Tabs/index.ts", to: "./Tabs/index.js" },
        { from: "./src/Table/index.ts", to: "./Table/index.js" },
        { from: "./src/TextArea/index.ts", to: "./TextArea/index.js" },
        { from: "./src/TextBox/index.ts", to: "./TextBox/index.js" },
        { from: "./src/TextBoxGroup/index.ts", to: "./TextBoxGroup/index.js" },
        { from: "./src/TextLabel/index.ts", to: "./TextLabel/index.js" },
        { from: "./src/Timeline/index.ts", to: "./Timeline/index.js" },
        { from: "./src/Timepicker/index.ts", to: "./Timepicker/index.js" },
        { from: "./src/Toggle/index.ts", to: "./Toggle/index.js" },
        { from: "./src/Tooltip/index.ts", to: "./Tooltip/index.js" },
        { from: "./src/Video/index.ts", to: "./Video/index.js" },
        { from: "./src/ImageCropper/index.ts", to: "./ImageCropper/index.js" },
        { from: "./src/Timer/index.ts", to: "./Timer/index.js" }
    ]
};
